// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkbjghqhitzhohkhqdla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrYmpnaHFoaXR6aG9oa2hxZGxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjI2NTksImV4cCI6MjA2MTAzODY1OX0.SVcK0oI8J3u9IVL-3qHG5bL8hBfS6PDY2wj1MkUZyXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);